version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: true
permissions:
  - object: /home/ec2-use/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root
